dependencies:
  "@hapi/joi": 17.1.1
  "@ngiq/nodejs-common": 1.3.4
  bunyan: 1.8.15
  cls-hooked: 4.2.2
  ejs: 3.1.6
  express: 4.17.3
  helmet: 5.0.2
  lodash: 4.17.21
  uuid: 8.3.2
  '@alicloud/fc2': 2.5.4
  '@alicloud/kms20160120': 2.0.1
  '@alicloud/openapi-client': 0.4.1
  ali-oss: 6.17.1
  aws-sdk: 2.1117.0
  fs-extra: 10.1.0
  ini: 3.0.0
  axios: 0.26.1
  '@pipcook/boa': 1.3.1
dependenciesOnly:
  bunyan:
    - "@ngiq/nodejs-common"
  cls-hooked:
    - "@ngiq/nodejs-common"
devDependencies:
  "@types/bunyan": 1.8.8
  "@types/chai": 4.3.0
  "@types/cls-hooked": 4.3.3
  "@types/ejs": 3.1.0
  "@types/express": 4.17.13
  "@types/express-serve-static-core": 4.17.2
  "@types/hapi__joi": 17.1.8
  "@types/helmet": 4.0.0
  "@types/joi": 17.2.3
  "@types/lodash": 4.14.181
  "@types/mocha": 9.1.0
  "@types/mz": 2.7.4
  "@types/shelljs": 0.8.11
  "@types/sinon": 10.0.11
  '@types/sinon-chai': 3.2.8
  "@types/supertest": 2.0.12
  "@types/uuid": 8.3.4
  "@typescript-eslint/eslint-plugin": 5.19.0
  "@typescript-eslint/parser": 5.19.0
  chai: 4.3.6
  clarify: 2.1.0
  eslint: 8.13.0
  eslint-config-prettier: 8.5.0
  eslint-plugin-import: 2.26.0
  eslint-plugin-jest: 26.1.4
  eslint-plugin-jsdoc: 39.1.1
  eslint-plugin-lodash: 7.4.0
  eslint-plugin-no-null: 1.0.2
  eslint-plugin-prefer-arrow: 1.2.3
  eslint-plugin-security: 1.4.0
  eslint-plugin-unicorn: 42.0.0
  jscpd: 3.4.5
  json-schema: 0.2.5
  json-schema-ref-parser: 7.1.4
  json-schema-to-joi: 5.1.0
  json-schema-to-typescript: 8.1.0
  mocha: 9.2.2
  mochawesome: 7.1.3
  mrm: 4.0.0
  mz: 2.7.0
  nyc: 15.1.0
  openapi-types: 1.3.5
  scripty: 2.1.0
  shelljs: 0.8.5
  source-map-support: 0.5.21
  swagger-parser: 8.0.4
  trace: 3.1.1
  ts-node: 10.7.0
  tsc-watch: 5.0.3
  typescript: 4.6.3
  typescript-formatter: 7.2.2
  nodemon: 2.0.15
  doctoc: 2.1.0
  node-fetch: 2.6.0
  plantuml-encoder: 1.4.0
  redoc-cli: 0.13.10
  '@types/ini': 1.3.31
  sinon-chai: 3.7.0
  sinon: 13.0.1
  supertest: 6.2.2
  '@types/chai-subset': 1.3.3
  '@types/fs-extra': 9.0.13
  chai-subset: 1.6.0
resolutions:
  "@ngiq/nodejs-common": "*"
  typescript: "*"

